apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-cfg.yaml
- prometheus-dep.yaml
- prometheus-rbac.yaml
- prometheus-svc.yaml
- prometheus-svc-lb.yaml
- prometheus-pvc.yaml
