apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: padogrid-template
  app: ${APP_NAME}
  role: hazelcast
metadata:
  annotations:
    description: PadoGrid
  name: padogrid

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${APP_NAME}
      spec:
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
        containers:
        - image: docker.io/padogrid/padogrid:latest
          name: padogrid
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HAZELCAST_SERVICE
            value: ${HAZELCAST_SERVICE}
          - name: HAZELCAST_CLUSTER_NAME
            value: ${HAZELCAST_CLUSTER_NAME}
parameters:
- description: The application name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: padogrid
- description: Hazelcast service
  displayName: Hazelcast service
  name: HAZELCAST_SERVICE
  required: false
  value: hazelcast
- description: Hazelcast cluster name
  displayName: Hazelcast cluster name
  name: HAZELCAST_CLUSTER_NAME
  required: false
  value: dev
